### ISSUE TITLE
WebLink for Bacillus subtilis in sources.txt leads to an entry for Enterococcus faecium

### ISSUE THREAD

**Issue by kevinxchan** [LomanLab/mockcommunity#16]
Hi, I'm interested in using the R10 dataset for some benchmarking, and one thing I wanted to do was to download all the reference genomes provided in `sources.txt`. 

However, if you follow the [web link](https://www.ncbi.nlm.nih.gov/sviewer/viewer.cgi?tool=portal&log$=seqview&db=nuccore&report=fasta&id=1199772504&extrafeat=null&conwithfeat=on) for Bacillus subtilis (line 6), this leads to an entry for Enterococcus faecalis strain sorialis. 

Is this an incorrect entry in `sources.txt`, or something to be updated in the metadata, or other?

**Comment by SamStudio8** [comment]
Hi Kevin,
The `sources.txt` is a legacy file (sorry about that), which is not actually used as part of our analysis. We have [Illumina draft assemblies of the isolates](http://nanopore.s3.climb.ac.uk/mockcommunity/v2/Zymo-Isolates-SPAdes-Illumina.fasta). Additionally McIntyre et al. have recently made [PacBio isolates draft assemblies](https://github.com/al-mcintyre/mCaller_analysis_scripts/tree/master/assemblies) available too.

**Comment by SamStudio8** [comment]
Bad file removed in 02137f47c495af131aafe3c82365b18b6352f8b3

**Comment by kevinxchan** [comment]
Thanks for the quick reply. But I'm interested in getting the annotated genomes used in this mock community - do you have a mapping from the strains used to their NCBI entry or something similar?

**Comment by SamStudio8** [comment]
Hi Kevin, we have corresponding NRRL accessions for the strains ([see our preprint](https://www.biorxiv.org/content/10.1101/487033v2)), but there is not necessarily a fully annotated genome for each particular strain in the NCBI, which led us to use draft references in our work.
