### ISSUE TITLE
invalid compressed data--format violated

### ISSUE THREAD

**Issue by BigNianNGS** [LomanLab/mockcommunity#18]
After i downloaded the R10 GridION gz file,  it occurs that ”gzip: Zymo-GridION-EVEN-BB-SN-PCR-R10HC-flipflop.fq.gz: invalid compressed data--format violated”.

Linux system and downloading command： wget -c https://s3.climb.ac.uk/nanopore/Zymo-GridION-EVEN-BB-SN-PCR-R10HC-flipflop.fq.gz

is it a command erro ?

**Comment by SamStudio8** [comment]
Hi Nian,
It seems to extract OK on my end:

```
$ wget -c https://s3.climb.ac.uk/nanopore/Zymo-GridION-EVEN-BB-SN-PCR-R10HC-flipflop.fq.gz
$ gunzip Zymo-GridION-EVEN-BB-SN-PCR-R10HC-flipflop.fq.gz
$ head Zymo-GridION-EVEN-BB-SN-PCR-R10HC-flipflop.fq  -n1                                                                                                                                                                        
@46a0b354-9b84-4614-a78d-437c7bb46208 runid=e82762e88e02db56f62eae53f73802242dabd13b sampleid=Zymo-GridION-EVEN-BB-SN-PCR-R10HC read=57119 ch=507 start_time=2018-11-21T03:27:04Z
```

The `md5sum` of the downloaded gz should be `666b66c81cec0361b3817a97d0a02c96`, can you confirm that is what you have?
