### ISSUE TITLE
species of R10 data

### ISSUE THREAD

**Issue by yangxiaofeill** [LomanLab/mockcommunity#19]
Dear,
    I head a talk today, and the speaker introduced the R10, which is much more accurate than R9.4.  I am interested in the R10 data and found this github site. I wonder what is the species of the data `https://s3.climb.ac.uk/nanopore/Zymo-GridION-EVEN-BB-SN-PCR-R10HC-flipflop.fq.gz`    and    `https://s3.climb.ac.uk/nanopore/Zymo-GridION-EVEN-BB-SN-PCR-R10HC_multi.tar`. And also, I would like to know the coverage of this dataset.

Thanks very much.

Best
Xiaofei

**Comment by SamStudio8** [comment]
Hi Xiaofei,
The datasets in this project are sequencing runs of the [ZymoBIOMICS Microbial Community Standard](https://www.zymoresearch.com/collections/zymobiomics-microbial-community-standards), which is a mock community consisting of ten organisms. `Zymo-GridION-EVEN-BB-SN-PCR-R10HC-flipflop.fq.gz` is the basecalled data from a sequencing run on the R10, and the `Zymo-GridION-EVEN-BB-SN-PCR-R10HC_multi.tar` is the corresponding multi-FAST5 signal.

The sequencing libraries were derived from @joshquick's ["Samurai" PCR protocol](https://docs.google.com/document/d/1afH4JGYDrBVYNxBvErE0Z-NHdCF-uWKL75kwp3bLHDE/edit?usp=sharing).
