### ISSUE TITLE
Fast5 file download

### ISSUE THREAD

**Issue by ttbond** [LomanLab/mockcommunity#20]
Hi, I want to know if I can download the fast5 file by aspera because wget is too slow to download the 271GB file.

**Comment by nickloman** [comment]
You should be able to get it via the EBI's Aspera service. Check the manuscript for the relevant accessions. More details here: https://www.ebi.ac.uk/ena/browse/read-download#downloading_files_aspera

**Comment by ttbond** [comment]
But there is only a download link from climb(in https style), I don't knwo where to get the ftp address of the fast5 file of ebi.

**Comment by SamStudio8** [comment]
@ttbond You'll want to use the files hosted at the EBI using the instructions that @nickloman linked you. You can see all the files pertaining via [ENA study PRJEB29504](https://www.ebi.ac.uk/ena/data/view/PRJEB29504).
