### ISSUE TITLE
Not able to access specification sheet

### ISSUE THREAD

**Issue by prashantpandey** [LomanLab/mockcommunity#23]
Hi,

We are trying to access the ground truth but the link is not accessible. (https://www.zymoresearch.eu/media/amasty/amfile/attach/_D6300_ZymoBIOMICS_Microbial_Community_Standard_v1.1.3.pdf)

Could you please give us another link or upload the specification sheet here. 

Thanks,
Prashant

**Comment by SamStudio8** [comment]
For future users, the specifications are now kept on this repo: https://github.com/LomanLab/mockcommunity/tree/master/specs
